// Regenerates the area lists from scripts/lagos_areas.json, the one place areas
// are edited by hand. Run from the repo root after changing that file:
//
//   node scripts/gen_areas.js
//
// It rewrites, between the GENERATED markers:
//   lib/core/utils/inspection_pricing.dart       the app's compiled baseline
//   ../clearrent_web/lib/lagos-areas.ts          the web listing form's copy
//   ../clearrent_admin/src/lib/lgas.generated.ts the LGAs admin can file into
//
// Web used to be kept in step by hand, which is how the two drifted. Areas can
// still be added live from the admin dashboard (config/areas); this file is only
// the offline baseline that ships in the app.
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const WEB = path.resolve(ROOT, "..", "clearrent_web");
const data = JSON.parse(fs.readFileSync(path.join(ROOT, "scripts", "lagos_areas.json"), "utf8"));

const q = (s) => "'" + s.replace(/'/g, "\\'") + "'";
const byLga = (lga) => Object.keys(data.areas).filter((a) => data.areas[a] === lga).sort();

function check() {
  const keys = new Set(data.lgas.map((l) => l.key));
  for (const [area, lga] of Object.entries(data.areas)) {
    if (!keys.has(lga)) throw new Error(`area "${area}" has unknown LGA "${lga}"`);
    if (area !== area.trim().toLowerCase()) throw new Error(`area key "${area}" is not lowercase`);
  }
  for (const [alias, target] of Object.entries(data.aliases)) {
    if (!(target in data.areas)) throw new Error(`alias "${alias}" points at missing area "${target}"`);
    if (alias in data.areas) throw new Error(`"${alias}" is both an area and an alias`);
  }
}

function dartBlock() {
  const out = [];
  out.push("  /// Lagos LGAs in display order: what every area picker opens on.");
  out.push("  static const List<String> lgas = [");
  for (const l of data.lgas) out.push(`    ${q(l.key)},`);
  out.push("  ];");
  out.push("");
  out.push("  /// The state each LGA is in. An area picked from the list decides the");
  out.push("  /// state, so this is what stops an Ogun area saving as Lagos.");
  out.push("  static const Map<String, String> _lgaState = {");
  for (const l of data.lgas) out.push(`    ${q(l.key)}: ${q(l.state)},`);
  out.push(`    outerLGA: 'Lagos',`);
  out.push("  };");
  out.push("");
  out.push("  static const Map<String, String> _lgaLabels = {");
  for (const l of data.lgas) out.push(`    ${q(l.key)}: ${q(l.label)},`);
  out.push(`    outerLGA: 'Outer Lagos',`);
  out.push(`    otherLGA: 'Other areas',`);
  out.push("  };");
  out.push("");
  out.push("  /// Compiled-in area to LGA map (lowercase keys). The offline baseline.");
  out.push("  static const Map<String, String> _defaultAreaToLGA = {");
  for (const l of data.lgas) {
    const areas = byLga(l.key);
    if (!areas.length) continue;
    out.push(`    // ${l.label}`);
    for (const a of areas) out.push(`    ${q(a)}: ${q(l.key)},`);
    out.push("");
  }
  out.push("  };");
  out.push("");
  out.push("  /// Spellings and old names that must keep resolving, mapped onto the area");
  out.push("  /// they mean. They are deliberately NOT offered in the pickers, so one");
  out.push("  /// place is one row, but a listing or saved preference that used the old");
  out.push("  /// spelling still finds its LGA.");
  out.push("  static const Map<String, String> _areaAliases = {");
  for (const [alias, target] of Object.entries(data.aliases)) out.push(`    ${q(alias)}: ${q(target)},`);
  out.push("  };");
  return out.join("\n");
}

function webFile() {
  const out = [];
  out.push("/**");
  out.push(" * Lagos areas and the LGA each belongs to, for the web listing form.");
  out.push(" *");
  out.push(" * GENERATED by clearrent/scripts/gen_areas.js from scripts/lagos_areas.json.");
  out.push(" * Do not edit: run the generator so web and app always offer the same areas.");
  out.push(" * config/areas adds to this at runtime, exactly as it does in the app.");
  out.push(" */");
  out.push("");
  out.push("export const AREA_TO_LGA: Record<string, string> = {");
  for (const l of data.lgas) {
    const areas = byLga(l.key);
    if (!areas.length) continue;
    out.push(`  // ${l.label}`);
    for (const a of areas) out.push(`  '${a}': '${l.key}',`);
  }
  out.push("}");
  out.push("");
  out.push("/** Old spellings, resolved but never listed. */");
  out.push("export const AREA_ALIASES: Record<string, string> = {");
  for (const [alias, target] of Object.entries(data.aliases)) out.push(`  '${alias}': '${target}',`);
  out.push("}");
  out.push("");
  out.push("export const LGA_LABELS: Record<string, string> = {");
  for (const l of data.lgas) out.push(`  '${l.key}': '${l.label}',`);
  out.push("  outer: 'Outer Lagos',");
  out.push("  other: 'Other areas',");
  out.push("}");
  out.push("");
  out.push("/** The state each LGA is in. Unknown LGAs have no state, deliberately. */");
  out.push("export const LGA_STATE: Record<string, string> = {");
  for (const l of data.lgas) out.push(`  '${l.key}': '${l.state}',`);
  out.push("  outer: 'Lagos',");
  out.push("}");
  out.push("");
  out.push("/** Display order, busiest rental markets first, as in the app. */");
  out.push("export const LGA_ORDER: string[] = [");
  for (const l of data.lgas) out.push(`  '${l.key}',`);
  out.push("]");
  return out.join("\n") + "\n";
}

// Both targets are checked in with CRLF endings on this machine, so match
// whatever the file already uses instead of leaving it mixed.
function withEol(text, sample) {
  const lf = text.replace(/\r\n/g, "\n");
  return sample.includes("\r\n") ? lf.replace(/\n/g, "\r\n") : lf;
}

// The admin dashboard only needs the LGAs, to file a reported area into one.
// It used to keep a hand-copied list that was missing six of them, so an area
// in Apapa or Ojo could not be added at all.
function adminFile() {
  const out = [];
  out.push("/**");
  out.push(" * The LGAs an area can be filed into, and the state each one is in.");
  out.push(" *");
  out.push(" * GENERATED by clearrent/scripts/gen_areas.js from scripts/lagos_areas.json.");
  out.push(" * Do not edit. The app drops a published area whose LGA it does not know, so");
  out.push(" * this list has to match the app's, and a hand-kept copy did not.");
  out.push(" */");
  out.push("");
  out.push("export type LgaOption = { value: string; label: string; state: string }");
  out.push("");
  out.push("export const LGA_OPTIONS: LgaOption[] = [");
  for (const l of data.lgas) {
    out.push(`  { value: ${JSON.stringify(l.key)}, label: ${JSON.stringify(l.label)}, state: ${JSON.stringify(l.state)} },`);
  }
  out.push('  { value: "other", label: "Other areas (outside our states)", state: "" },');
  out.push("]");
  return out.join("\n") + "\n";
}

function replaceBlock(file, block) {
  const src = fs.readFileSync(file, "utf8");
  const start = "// GENERATED-AREAS-START";
  const end = "// GENERATED-AREAS-END";
  const a = src.indexOf(start);
  const b = src.indexOf(end);
  if (a < 0 || b < 0) throw new Error(`markers missing in ${file}`);
  const head = src.slice(0, a + start.length);
  const tail = src.slice(b);
  fs.writeFileSync(file, head + withEol(`\n${block}\n  `, src) + tail);
}

check();
replaceBlock(path.join(ROOT, "lib", "core", "utils", "inspection_pricing.dart"), dartBlock());
const webTarget = path.join(WEB, "lib", "lagos-areas.ts");
const webHelpers = fs.existsSync(webTarget)
  ? fs.readFileSync(webTarget, "utf8").split("// ── Helpers (hand-written, below the generated data) ─")[1]
  : null;
const webSrc = fs.existsSync(webTarget) ? fs.readFileSync(webTarget, "utf8") : "";
fs.writeFileSync(
  webTarget,
  withEol(
    webFile() + (webHelpers ? "\n// ── Helpers (hand-written, below the generated data) ─" + webHelpers : ""),
    webSrc,
  ),
);
const ADMIN = path.resolve(ROOT, "..", "clearrent_admin");
const adminTarget = path.join(ADMIN, "src", "lib", "lgas.generated.ts");
const adminSrc = fs.existsSync(adminTarget) ? fs.readFileSync(adminTarget, "utf8") : "";
fs.writeFileSync(adminTarget, withEol(adminFile(), adminSrc));

console.log(
  `${data.lgas.length} LGAs, ${Object.keys(data.areas).length} areas, ` +
    `${Object.keys(data.aliases).length} aliases -> inspection_pricing.dart, ` +
    `lagos-areas.ts, lgas.generated.ts`,
);
